package com.fancye.wx.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setRmid(java.lang.String rmid) {
		set("rmid", rmid);
	}
	
	public java.lang.String getRmid() {
		return getStr("rmid");
	}

	public void setAppType(java.lang.Integer appType) {
		set("app_type", appType);
	}
	
	public java.lang.Integer getAppType() {
		return getInt("app_type");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public void setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
	}
	
	public java.lang.String getAppSecret() {
		return getStr("app_secret");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

	public void setEncrypt(java.lang.Integer encrypt) {
		set("encrypt", encrypt);
	}
	
	public java.lang.Integer getEncrypt() {
		return getInt("encrypt");
	}

	public void setEncryptKey(java.lang.String encryptKey) {
		set("encrypt_key", encryptKey);
	}
	
	public java.lang.String getEncryptKey() {
		return getStr("encrypt_key");
	}

	public void setMchId(java.lang.String mchId) {
		set("mch_id", mchId);
	}
	
	public java.lang.String getMchId() {
		return getStr("mch_id");
	}

	public void setApiKey(java.lang.String apiKey) {
		set("api_key", apiKey);
	}
	
	public java.lang.String getApiKey() {
		return getStr("api_key");
	}

	public void setCertPath(java.lang.String certPath) {
		set("certPath", certPath);
	}
	
	public java.lang.String getCertPath() {
		return getStr("certPath");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}
	
	public java.lang.String getDomain() {
		return getStr("domain");
	}

	public void setSubscribeUrl(java.lang.String subscribeUrl) {
		set("subscribe_url", subscribeUrl);
	}
	
	public java.lang.String getSubscribeUrl() {
		return getStr("subscribe_url");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
