package com.fancye.wx.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public void setSubscribeTime(java.lang.String subscribeTime) {
		set("subscribe_time", subscribeTime);
	}
	
	public java.lang.String getSubscribeTime() {
		return getStr("subscribe_time");
	}

	public void setUnsubscribeTime(java.lang.String unsubscribeTime) {
		set("unsubscribe_time", unsubscribeTime);
	}
	
	public java.lang.String getUnsubscribeTime() {
		return getStr("unsubscribe_time");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public void setPrivilege(java.lang.String privilege) {
		set("privilege", privilege);
	}
	
	public java.lang.String getPrivilege() {
		return getStr("privilege");
	}

	public void setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
	}
	
	public java.lang.String getHeadimgurl() {
		return getStr("headimgurl");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
