package com.fancye.wx.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthorize<M extends BaseAuthorize<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}
	
	public java.lang.String getDomain() {
		return getStr("domain");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setSnsapiBase(java.lang.Integer snsapiBase) {
		set("snsapiBase", snsapiBase);
	}
	
	public java.lang.Integer getSnsapiBase() {
		return getInt("snsapiBase");
	}

	public void setSubscribeUrl(java.lang.String subscribeUrl) {
		set("subscribe_url", subscribeUrl);
	}
	
	public java.lang.String getSubscribeUrl() {
		return getStr("subscribe_url");
	}

	public void setRedirectUri(java.lang.String redirectUri) {
		set("redirect_uri", redirectUri);
	}
	
	public java.lang.String getRedirectUri() {
		return getStr("redirect_uri");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
