package com.fancye.wx.comm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRedpack<M extends BaseRedpack<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public void setSendName(java.lang.String sendName) {
		set("send_name", sendName);
	}
	
	public java.lang.String getSendName() {
		return getStr("send_name");
	}

	public void setTotalAmount(java.lang.Integer totalAmount) {
		set("total_amount", totalAmount);
	}
	
	public java.lang.Integer getTotalAmount() {
		return getInt("total_amount");
	}

	public void setTotalNum(java.lang.Integer totalNum) {
		set("total_num", totalNum);
	}
	
	public java.lang.Integer getTotalNum() {
		return getInt("total_num");
	}

	public void setWishing(java.lang.String wishing) {
		set("wishing", wishing);
	}
	
	public java.lang.String getWishing() {
		return getStr("wishing");
	}

	public void setActName(java.lang.String actName) {
		set("act_name", actName);
	}
	
	public java.lang.String getActName() {
		return getStr("act_name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setSceneId(java.lang.String sceneId) {
		set("scene_id", sceneId);
	}
	
	public java.lang.String getSceneId() {
		return getStr("scene_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
