package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
}
