package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseAuthorize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authorize extends BaseAuthorize<Authorize> {
	public static final Authorize dao = new Authorize().dao();
}
