package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseCustommenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Custommenu extends BaseCustommenu<Custommenu> {
	public static final Custommenu dao = new Custommenu().dao();
}
