package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseKeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Keyword extends BaseKeyword<Keyword> {
	public static final Keyword dao = new Keyword().dao();
}
