package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseMatchrulemenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Matchrulemenu extends BaseMatchrulemenu<Matchrulemenu> {
	public static final Matchrulemenu dao = new Matchrulemenu().dao();
}
