package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Material extends BaseMaterial<Material> {
	public static final Material dao = new Material().dao();
}
