package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseMenutype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menutype extends BaseMenutype<Menutype> {
	public static final Menutype dao = new Menutype().dao();
}
