package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseQrcode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Qrcode extends BaseQrcode<Qrcode> {
	public static final Qrcode dao = new Qrcode().dao();
}
