package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseRedpack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Redpack extends BaseRedpack<Redpack> {
	public static final Redpack dao = new Redpack().dao();
}
