package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseReplymessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Replymessage extends BaseReplymessage<Replymessage> {
	public static final Replymessage dao = new Replymessage().dao();
}
