package com.fancye.wx.comm.model;

import com.fancye.wx.comm.model.base.BaseSubmsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Submsg extends BaseSubmsg<Submsg> {
	public static final Submsg dao = new Submsg().dao();
}
